import { create } from 'zustand'

const useStateStore = create((set) => ({
    allianceColor: "red",
    allianceStation: 1,
    scoutName: "",
    matchNumber: "",
    teamNumber: "",
    preload: false,
    noShow: false,
    startPosition: "a",
    rotateField: false,
    reefAutonL1Count: 0, 
    reefAutonL2Count: 0,
    reefAutonL3Count: 0,
    reefAutonL4Count: 0,
    reefAutonL1MissCount: 0,
    reefAutonL2MissCount: 0,
    reefAutonL3MissCount: 0,
    reefAutonL4MissCount: 0,
    processorAutonCount: 0,
    processorAutonMissCount: 0,
    netAutonCount: 0,
    netAutonMissCount: 0,
    reefTeleopL1Count: 0, 
    reefTeleopL2Count: 0,
    reefTeleopL3Count: 0,
    reefTeleopL4Count: 0,
    reefTeleopL1MissCount: 0,
    reefTeleopL2MissCount: 0,
    reefTeleopL3MissCount: 0,
    reefTeleopL4MissCount: 0,
    processorTeleopCount: 0,
    processorTeleopMissCount: 0,
    netTeleopCount: 0,
    netTeleopMissCount: 0,
    matchData: {},
    set
}))
export default useStateStore;